# Generated by Django 5.1.1 on 2025-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_quotation_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hide_from_highlights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='super_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='extra_head_html',
            field=models.TextField(blank=True, help_text="Extra HTML to be included in the &lt;head&gt; for this entry e.g. <a href='https://til.simonwillison.net/django/live-blog' target='_blank'>Live javascript</a>", null=True),
        ),
    ]
